import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PlantsHarmony",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon.ico"],
    // apple: ["/images/apple-touch-icon.png?v=4"],
    // shortcut: ["/images/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" data-theme="dark">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
