import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "PlantsHarmony",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon.ico"],
  },
};
